### ISSUE TITLE
Konfigurationsdateien

### ISSUE THREAD

**Issue by mweinelt** [PumucklOnTheAir/TestFramework#87]
Die Konfiguration ist über mehrere Dateien verteilt. Die Struktur der YAML-Dateien ist ungewöhnlich:
```yaml
--- # Configuration for config the Router's manual
# Insert for each Router one newline with the follow informations
# Name: , Id: , IP: , IP_Mask: , CONFIG_IP , CONFIG_IP_MASK , Username: , Password: , PowerSocket:
- {Name: vlan21, Id: 21, IP: 10.223.254.254, IP_Mask: 16, CONFIG_IP: 192.168.1.1, CONFIG_IP_MASK: 24, Username: root, Password: root, PowerSocket: 1}
- {Name: vlan22, Id: 22, IP: 10.223.254.254, IP_Mask: 16, CONFIG_IP: 192.168.1.1, CONFIG_IP_MASK: 24, Username: root, Password: root, PowerSocket: 2}
- {Name: vlan23, Id: 23, IP: 10.223.254.254, IP_Mask: 16, CONFIG_IP: 192.168.1.1, CONFIG_IP_MASK: 24, Username: root, Password: root, PowerSocket: 3}
```

Eine YAML-Datei unterstützt sehr elegant "nested" Strukturen, dazu müsste man dann z.B. im folgenden fall die entstehenden dictionaries mergen, hätte dann default Values und wäre viel lesbarer unterwegs..
```yaml
default:
  vlan_name: vlan{id} # z.B. format string: vlan_name.format(id=vlan_id)
  config_mode:
    ip4_addr: 192.168.1.1
    ip4_netmask: 24
  running:
    ip4_addr: 10.223.254.254
    ip4_netmask: 16
    ssh:
      user: root
      password: root
nodes:
  - vlan_id: 21
    pwr_socket: 1
    # elements from default could be overwritten by merging with `defaults`
    running:
      ssh:
        user: foo
        password: bar
  - vlan_id: 22
    pwr_socket: 2
  - vlan_id: 23
    pwr_socket: 3
```

Insgesamt könnte man so auch mehrere Konfigurationsdateien in eine mit ein paar Sections und Kommentaren migrieren.
